version: "3"

services:
  nginx:
    container_name: "aibou-nginx"
    build:
      context: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./:/src

  php:
    container_name: "aibou-php"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      
  db:
    image: mariadb:10.9
    container_name: "aibou-db"
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aibou